echo "R11: for phase 2 the following QuotaNames are allowed for postpaid: "
echo "   and (   (Quota_Name == 'Q_23_local_Month') "
echo "        or (Quota_Name == 'Q_68_local_Month') "
echo "        or (Quota_Name == 'Q_72_local_Month') "
echo "        or (Quota_Name == 'Q_74_local_Month') "
echo "        or (Quota_Name == 'Q_81_local_Month') "
echo "        or (Quota_Name == 'Q_109_local_Month') "
echo "        or (Quota_Name == 'Q_117_local_Month') "
echo "        or (Quota_Name == 'Q_127_local_Month')"
echo "        or (Quota_Name == 'Q_25_local_Month')"
echo "        or (Quota_Name == 'Q_37_local_Month')"
echo "        or (Quota_Name == 'Q_73_local_Month')"
echo "        or (Quota_Name == 'Q_91_local_Month')"
echo "        or (Quota_Name == 'Q_93_local_Month')"
echo "        or (Quota_Name == 'Q_108_local_Month')"
echo "        or (Quota_Name == 'Q_110_local_Month')"
echo "        or (Quota_Name == 'Q_111_local_Month')"
echo "        or (Quota_Name == 'Q_124_local_Month')"
echo "        or (Quota_Name == 'Q_131_local_Month') )"
echo " "
echo " "
