#!/bin/bash

echo "stopping all cep components.."

./STOP_CEP_ADAPTER.sh
./STOP_CEP_MODEL.sh POSTPAID_THROTTLE_EVENT
./STOP_CEP_MODEL.sh PREPAID_THROTTLE_EVENT
./STOP_CEP_MODEL.sh FONIC_THROTTLE_EVENT
./STOP_CEP_ENGINE.sh

